### ISSUE TITLE
Uncaught ReferenceError: reg is not defined floatingText.js:290

### ISSUE THREAD

**Issue by spiritabsolute** [netgfx/Phaser-FloatingText#1]
In handler function tweenObj.onComplete.addOnce( , you must explicitly define an object reg.
`var reg = {};`

Error repetition:
`
new FloatingText(this, {
        text: text,
        animation: "up",
        textOptions: {
            font: "20px "+this.defaultFont,
            fill: "#181410"
        },
        x: this.game.width/2,
        y: this.game.height/2,
        timeToLive: 1000
    });
`

**Comment by netgfx** [comment]
issue should be fixed now, please check with latest code.

thanks!
