### ISSUE TITLE
Class not compatible with Phaser 3

### ISSUE THREAD

**Issue by goedzo** [netgfx/Phaser-FloatingText#2]
I tried to use this class in a Phaser 3 project, but it results in a lot of issues. Can this be updated for Phaser 3 support please?

**Comment by netgfx** [comment]
I don't think it can be updated to work with phaser 3, but I can try to release a new phaser 3 plugin for it.

**Comment by netgfx** [comment]
@goedzo new v3 plugin https://github.com/netgfx/FloatingNumbersPlugin
